---
# tasks file for awx
- name: Installing boto.
  pip:
    name: boto

- name: Launch instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget epel-release -y
      yum install git ansible python-pip -y
      pip install virtualenv
      wget -O- https://get.docker.com/ | sh
      systemctl start docker
      systemctl enable docker
      systemctl status -l docker
      wget -O awx.yaml https://gist.github.com/hemanth22/17c3234c0b4b9e3f323ff0f3033dfc2c/raw
      ansible-playbook awx.yaml
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: awx
      Environment: Production
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
